editor nvim

# hints
# open URL
map ctrl+shift+e kitten hints 
# insert path
map ctrl+shift+p>f kitten hints --type path --program -
# insert line
map ctrl+shift+p>l kitten hints --type line --program -
# insert word
map ctrl+shift+p>w kitten hints --type word --program -
# insert git hash
map ctrl+shift+p>h kitten hints --type hash --program -
# open file:line in nvim
map ctrl+shift+p>n kitten hints --type linenum
# open hyperlink in browser
map ctrl+shift+p>y kitten hints --type hyperlink

notify_on_cmd_finish always
macos_option_as_alt both
macos_quit_when_last_window_closed yes
shell_integration enabled
font_size 14
allow_remote_control yes
listen_on unix:/tmp/mykitty-{kitty_pid}
text_fg_override_threshold 4.5 ratio

window_margin_width 5 10
single_window_margin_width 0
window_padding_width 10

tab_bar_style separator
tab_separator " | "
tab_bar_edge left
tab_bar_width 240
tab_bar_auto_width yes
tab_activity_symbol "⏳ "
tab_title_template "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{tab.last_focused_progress_percent}{index}:{title}"

enabled_layouts Tall, Stack, Grid, Fat

map f1 toggle_tab_bar
map f2 launch --type=os-window /opt/homebrew/bin/nvim ~/todo.md
map cmd+enter new_window_with_cwd
map ctrl+1 goto_tab 1
map ctrl+2 goto_tab 2
map ctrl+3 goto_tab 3
map ctrl+4 goto_tab 4
map ctrl+5 goto_tab 5
map ctrl+6 goto_tab 6
map ctrl+7 goto_tab 7
map ctrl+8 goto_tab 8
map ctrl+9 goto_tab 9
map kitty_mod+j next_tab
map kitty_mod+k previous_tab

