include ./theme.conf
editor .
notify_on_cmd_finish always
macos_option_as_alt both
shell_integration enabled
font_size 14
window_margin_width     3
single_window_margin_width 0

tab_bar_style separator
tab_separator " | "
tab_bar_edge top
tab_activity_symbol "🔔 "
tab_title_template "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{tab.last_focused_progress_percent}{index}:{title}"

enabled_layouts Fat, Grid, Tall

background_color #000000
background_tint 0.97
background_tint_gaps 0.10

map f1 launch /opt/homebrew/bin/nvim ~/todo
map kitty_mod+p>v kitten hints --type=linenum --linenum-action=background -- cursor -g {path}:{line}:0
map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5
map alt+6 goto_tab 6
map alt+7 goto_tab 7
map alt+8 goto_tab 8
map alt+9 goto_tab 9
